import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const root = new URL('../../', import.meta.url);
for (const [name, symbol] of [
  ['vFrame', 'vframeAbi'],
  ['VFrameAccountFactory', 'factoryAbi'],
  ['VFrameAccount', 'accountAbi'],
]) {
  const artifact = JSON.parse(
    readFileSync(new URL(`vframe/out/${name}.sol/${name}.json`, root), 'utf8'),
  );
  writeFileSync(
    fileURLToPath(new URL(`web/lib/${symbol}.ts`, root)),
    `// Generated by npm run sync-abi after forge build --root vframe.\nexport const ${symbol} = ${JSON.stringify(artifact.abi)} as const;\n`,
  );
}
